language: node_js
node_js: stable
dist: trusty
sudo: required
os:
  - linux
  - osx
osx_image: xcode7.3
branches:
  only:
    - master  
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run pree2e
